import os
from dotenv import load_dotenv

load_dotenv()

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
SESSION_SECRET_KEY = os.getenv("SESSION_SECRET_KEY")
REFRESH_TOKEN_EXPIRE_DAYS = os.getenv('REFRESH_TOKEN_EXPIRE_DAYS')
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv('ACCESS_TOKEN_EXPIRE_MINUTES')
ACCESS_SECRET = os.getenv("JWT_ACCESS_SECRET")
ACCESS_COOKIE_NAME = os.getenv("ACCESS_COOKIE_NAME")
REFRESH_SECRET = os.getenv("JWT_REFRESH_SECRET")
REFRESH_COOKIE_NAME = os.getenv("REFRESH_COOKIE_NAME")
JWT_ALGORITHM = "HS256"

